---
deployment:
  tasks:
    - /bin/bash -lc 'set -e'
    - /bin/bash -lc 'SRC="$HOME/repositories/DomusGest/backend/public"; DST="$HOME/public_html"; mkdir -p "$DST"'
    - /bin/bash -lc 'find "$DST" -mindepth 1 -maxdepth 1 ! -name ".well-known" ! -name ".htaccess" -exec rm -rf {} +'
    - /bin/bash -lc 'cp -a "$SRC"/. "$DST"/'
    - /bin/bash -lc 'if [ ! -f "$DST/.htaccess" ]; then cat > "$DST/.htaccess" <<'\''HTX'\''; fi'
    - /bin/bash -lc 'cat > "$DST/.htaccess" <<'\''HTX'\'''
    - /bin/bash -lc 'DirectoryIndex index.html index.php'
    - /bin/bash -lc '<IfModule mod_rewrite.c>'
    - /bin/bash -lc '  RewriteEngine On'
    - /bin/bash -lc '  RewriteBase /'
    - /bin/bash -lc '  RewriteCond %{REQUEST_FILENAME} -f [OR]'
    - /bin/bash -lc '  RewriteCond %{REQUEST_FILENAME} -d'
    - /bin/bash -lc '  RewriteRule ^ - [L]'
    - /bin/bash -lc '  RewriteRule . /index.html [L]'
    - /bin/bash -lc '</IfModule>'
    - /bin/bash -lc 'HTX'